version: '3'


services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    volumes:
      - ./sql/news_actions.sql:/docker-entrypoint-initdb.d/news_actions.sql
      - ./sql/personal_area.sql:/docker-entrypoint-initdb.d/personal_area.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
